const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=s=>String(s).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const state={level:'Beginner',topics:3,currentStory:0,currentSlide:0,saved:new Set(),activityStep:0,historyDone:false,calendarDay:20,archiveFilter:'All',investmentStep:0,investmentChoices:[],marketSymbol:'MPX',marketMarker:1,tradeRound:0,tradeAction:'Buy',tradeSize:10,tradeChoices:[]};
const stories=[
 {id:0,art:'art-rate',tag:'BREAKING · ECONOMY',impact:'HIGH IMPACT',headline:'Rates stay higher as inflation proves stubborn',summary:'The central bank held rates at 5.25%—and warned cuts may take longer than markets hoped.',assets:[['FTSE 100','−0.4%','down'],['GBP/USD','+0.6%','up']],sources:'Reuters · Central bank',time:'8 min ago',mins:'2 min'},
 {id:1,art:'art-chip',tag:'TECHNOLOGY',impact:'HIGH IMPACT',headline:'AI chip demand sends tech shares higher',summary:'A major chipmaker’s outlook reignited optimism—but the cost of building AI is still climbing.',assets:[['TECH 100','+1.8%','up'],['CHIPS','+3.2%','up']],sources:'Company filing · Reuters',time:'24 min ago',mins:'2 min'},
 {id:2,art:'art-oil',tag:'COMMODITIES',impact:'MEDIUM IMPACT',headline:'Oil jumps as supply risks return',summary:'Crude prices rose after new shipping disruption renewed fears about global energy supply.',assets:[['BRENT','$83.14','up'],['AIRLINES','−1.1%','down']],sources:'IEA · Reuters',time:'41 min ago',mins:'90 sec'},
 {id:3,art:'art-bitcoin',tag:'CRYPTO',impact:'VOLATILE',headline:'Bitcoin breaks back above $60,000',summary:'ETF inflows helped lift crypto prices, while traders watched for another burst of volatility.',assets:[['BTC','$61.4K','up'],['ETH','+1.7%','up']],sources:'Exchange data · FT',time:'1 hr ago',mins:'2 min'},
 {id:4,art:'art-airline',tag:'COMPANIES',impact:'MEDIUM IMPACT',headline:'Airline warns fares may fall this autumn',summary:'More seats and cautious travellers could squeeze prices—and profit margins with them.',assets:[['AIRLINE','−6.8%','down'],['OIL','+0.9%','up']],sources:'Company release · BBC',time:'2 hr ago',mins:'90 sec'},
 {id:5,art:'art-currency',tag:'CURRENCIES',impact:'WATCH',headline:'Dollar slips after weaker jobs data',summary:'A cooling labour market shifted rate expectations and moved currencies around the world.',assets:[['DXY','−0.5%','down'],['EUR/USD','+0.4%','up']],sources:'BLS · Reuters',time:'3 hr ago',mins:'2 min'}
];
const archiveStories=[
 'Markets rally as price growth cools','Retail sales surprise as shoppers stay resilient','Sterling rises after wage data','Banks brace for a slower rate-cut cycle','Gold climbs on haven demand','Tech shares recover from early sell-off','Oil falls as inventories build','House prices edge higher','Jobs data points to a cooling market','European shares gain on earnings','Bond yields jump after inflation surprise','China growth data misses forecasts','Crypto markets steady after volatility','Consumer confidence improves','Energy companies lead the FTSE','Central bank minutes split policymakers','Chip shares surge on AI demand','Airline margins squeezed by fuel costs','Dollar weakens before jobs report','Rates stay higher as inflation proves stubborn'
];
const simTitles=['Manage a portfolio during a sudden market fall','Choose a mortgage as rates change','Price an airline through an oil shock','Allocate capital in an AI boom','Protect an importer from currency swings','Read the clues in a company earnings report'];
function seedArchive(){
 let stored;try{stored=JSON.parse(localStorage.getItem('marketplay-daily-archive')||'null')}catch(e){stored=null}
 if(!stored){stored={started:'2026-08-01',days:{}};for(let day=1;day<=20;day++){stored.days[day]={stories:[{title:archiveStories[day-1],story:(day-1)%stories.length},{title:archiveStories[Math.max(0,day-2)],story:(day+2)%stories.length}],simulations:[{title:simTitles[(day-1)%simTitles.length]}]};if(day%3===0)stored.days[day].simulations.push({title:simTitles[(day+2)%simTitles.length]})}stored.days[20]={stories:stories.map((s,i)=>({title:s.headline,story:i})),simulations:[{title:'Invest through a sudden rate shock'},{title:'Run a business while rates stay high'}]};try{localStorage.setItem('marketplay-daily-archive',JSON.stringify(stored))}catch(e){}}
 return stored;
}
const dailyArchive=seedArchive();
const marketAssets={
 MPX:{name:'MarketPlay Index',price:152.46,change:1.24,color:'#42d99a',path:'M0 142 C28 137 40 146 63 126 S101 117 123 129 S158 96 181 101 S215 76 238 84 S271 61 296 66 S330 37 360 29',markers:[{x:18,y:70,time:'08:30',title:'Inflation report surprises',price:'£146.80',move:'−3.8%',story:'Hotter inflation pushed expected rate cuts further out. Higher-rate-sensitive shares fell first.'},{x:52,y:52,time:'12:00',title:'Central bank holds rates',price:'£149.15',move:'+1.6%',story:'The hold was expected. A calmer statement reduced fears of another increase and prices recovered.'},{x:82,y:31,time:'15:20',title:'Tech earnings beat forecasts',price:'£153.02',move:'+2.1%',story:'Stronger profit guidance lifted the index because technology companies carry a large weight.'}]},
 NXT:{name:'NextWave Chips',price:84.72,change:3.18,color:'#9a7bff',path:'M0 151 C32 143 52 147 74 138 S115 121 140 130 S176 88 202 92 S242 71 270 48 S320 43 360 21',markers:[{x:23,y:72,time:'09:10',title:'New export restrictions',price:'£79.10',move:'−4.2%',story:'Potential sales limits reduced expectations for overseas revenue.'},{x:58,y:46,time:'13:00',title:'AI order book updated',price:'£82.36',move:'+4.1%',story:'Management reported stronger confirmed demand from data-centre customers.'},{x:83,y:25,time:'15:35',title:'Broker upgrades forecast',price:'£84.90',move:'+2.3%',story:'A higher earnings forecast attracted buyers, although this remains analysis rather than a confirmed result.'}]},
 BNK:{name:'United Metro Bank',price:38.14,change:-1.07,color:'#ff6468',path:'M0 47 C30 43 54 55 78 49 S111 61 139 69 S180 58 205 83 S249 94 271 119 S319 113 360 144',markers:[{x:20,y:28,time:'08:05',title:'Rates stay higher',price:'£39.42',move:'+1.2%',story:'Higher rates can support lending margins, initially helping bank shares.'},{x:57,y:50,time:'11:45',title:'Arrears warning',price:'£38.76',move:'−2.4%',story:'The bank warned that more borrowers were missing payments, increasing expected credit losses.'},{x:82,y:75,time:'14:30',title:'Regulator requests review',price:'£38.10',move:'−1.7%',story:'Uncertainty about a regulatory review added a risk discount to the share price.'}]}
};
function showScreen(id){$$('.screen').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');window.scrollTo(0,0)}
function showMain(tab='today'){showScreen('main-screen');switchTab(tab)}
function switchTab(tab){$$('.tab-view').forEach(v=>v.classList.toggle('active',v.id===tab+'-view'));$$('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.nav===tab));window.scrollTo(0,0)}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),1900)}
function renderFeed(){
 $('#story-feed').innerHTML=stories.map((s,i)=>`<article class="news-card" data-story="${i}"><div class="hero ${s.art}"></div><div class="card-top"><span class="tag">${s.tag}</span><span class="impact">◆ ${s.impact}</span></div><div class="card-content"><div class="asset-row">${s.assets.map(a=>`<span class="asset-pill">${a[0]} <b class="${a[2]}">${a[1]}</b></span>`).join('')}</div><h2>${s.headline}</h2><p class="summary">${s.summary}</p><div class="meta"><span>${s.sources}</span><i class="source-dot"></i><span>${s.time}</span><i class="source-dot"></i><span>◷ ${s.mins}</span></div><div class="card-actions"><button class="explore-btn" data-open-story="${i}">Explore story →</button><button class="action-btn ${state.saved.has(i)?'saved':''}" data-save="${i}" aria-label="Save">${state.saved.has(i)?'▰':'▱'}</button><button class="action-btn" data-share="${i}" aria-label="Share">↗</button><button class="action-btn" data-hide="${i}" aria-label="Not interested">•••</button></div><div class="scroll-hint">SWIPE FOR NEXT STORY ↓</div></div></article>`).join('');
}
function renderSaved(){const c=$('#saved-content');if(!state.saved.size){c.innerHTML=`<div class="empty-state"><div class="empty-icon">▱</div><h3>Build your learning library</h3><p>Save stories to revisit the explanation, activity or sources later.</p><button class="btn primary" data-nav="today">Find a story</button></div>`;return}c.innerHTML=`<div class="saved-list">${[...state.saved].map(i=>{const s=stories[i];return `<div class="saved-item"><div class="saved-thumb ${s.art}"></div><div><b>${s.headline}</b><small>${s.tag} · ${s.mins}</small></div><button class="text-btn" data-save="${i}">×</button></div>`}).join('')}</div>`}
function renderCalendar(){
 const cells=[];for(let i=0;i<5;i++)cells.push('<span class="calendar-day empty"></span>');
 for(let day=1;day<=31;day++){const future=day>20;cells.push(`<button class="calendar-day ${future?'future':'has-data'} ${day===state.calendarDay?'selected':''}" data-calendar-day="${day}">${day}</button>`)}
 $('#calendar-grid').innerHTML=cells.join('');renderArchiveDay();
}
function renderArchiveDay(){
 const day=state.calendarDay,data=dailyArchive.days[day]||{stories:[],simulations:[]};
 const date=new Date(2026,7,day);$('#archive-date-label').textContent=date.toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long'}).toUpperCase();
 $('#archive-count').textContent=`${data.stories.length} ${data.stories.length===1?'story':'stories'} · ${data.simulations.length} ${data.simulations.length===1?'simulation':'simulations'}`;
 const storyItems=data.stories.map((item,i)=>`<button class="archive-item" data-archive-story="${item.story}"><div class="archive-thumb ${stories[item.story].art}"></div><div><span>STORY · ${stories[item.story].mins}</span><b>${item.title}</b><small>${stories[item.story].sources}</small></div><i>›</i></button>`);
 const simItems=data.simulations.map((item,i)=>`<button class="archive-item" data-investment="${i}"><div class="archive-thumb sim"></div><div><span>INVESTMENT SIM · 2 DECISIONS</span><b>${item.title}</b><small>About 2 minutes · Virtual money</small></div><i>›</i></button>`);
 let items=state.archiveFilter==='Stories'?storyItems:state.archiveFilter==='Simulations'?simItems:[...storyItems,...simItems];
 $('#archive-results').innerHTML=items.length?items.join(''):'<div class="archive-empty">Nothing stored for this filter.</div>';
 $('.filter-pill').textContent=`${state.archiveFilter} ▾`;
}
function openInvestment(){state.investmentReturn=$('.screen.active')?.id||'calendar-screen';state.investmentStep=0;state.investmentChoices=[];renderInvestment();showScreen('investment-screen')}
function renderInvestment(){
 const c=$('#investment-content'),p=$('.investment-progress i'),label=$('.investment-step');
 if(state.investmentStep===0){label.textContent='1 / 2';p.style.width='50%';c.innerHTML=`<div class="investment-body"><div class="simulation-visual"><span class="visual-badge">MARKET OPEN · 09:05</span><div class="crash-chart"><svg viewBox="0 0 340 70"><defs><linearGradient id="crashFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#ff3b3f" stop-opacity=".35"/><stop offset="1" stop-color="#ff3b3f" stop-opacity="0"/></linearGradient></defs><path class="chart-area" d="M0 8 L55 12 L88 18 L124 14 L157 27 L190 23 L225 51 L259 43 L291 59 L340 64 L340 70 L0 70Z"/><path d="M0 8 L55 12 L88 18 L124 14 L157 27 L190 23 L225 51 L259 43 L291 59 L340 64"/></svg></div><b class="visual-loss">−8.4%</b></div><span class="scenario-label">DECISION 1 · THE SHOCK</span><h2>The market falls before breakfast.</h2><p>A surprise inflation report makes investors expect higher rates for longer. Your diversified virtual portfolio drops £840 in one morning. You need to decide before the market closes.</p><div class="portfolio-strip"><div><span>PORTFOLIO</span><b>£9,160</b></div><div><span>TIME HORIZON</span><b>5 years</b></div><div><span>CASH BUFFER</span><b>6 months</b></div></div><div class="investment-options"><button class="investment-choice" data-investment-choice="Hold the portfolio"><span>A</span><div><b>Hold the portfolio</b><small>Stay with the five-year plan despite the shock</small></div></button><button class="investment-choice" data-investment-choice="Move 30% to cash"><span>B</span><div><b>Move 30% to cash</b><small>Reduce further losses but lock in part of today’s fall</small></div></button><button class="investment-choice" data-investment-choice="Invest spare cash"><span>C</span><div><b>Invest £500 of spare cash</b><small>Buy at lower prices and accept more short-term risk</small></div></button></div><div class="custom-strategy"><label>Have a different idea?</label><textarea id="custom-investment" maxlength="180" placeholder="Describe what you would do and why…"></textarea><button class="btn wide" data-action="submit-custom-investment">Use my strategy</button></div><p class="disclaimer">Virtual money only. This is an educational simulation, not personalised investment advice.</p></div>`
 }else if(state.investmentStep===1){label.textContent='2 / 2';p.style.width='100%';c.innerHTML=`<div class="investment-body"><div class="simulation-visual rebound"><span class="visual-badge">TWO WEEKS LATER</span><div class="crash-chart"><svg viewBox="0 0 340 70"><path d="M0 62 L44 55 L83 58 L122 42 L163 46 L205 30 L247 35 L293 18 L340 10"/></svg></div><b class="visual-loss up">+5.1%</b></div><span class="scenario-label">DECISION 2 · NEW INFORMATION</span><h2>Markets rebound—but uncertainty remains.</h2><p>Inflation is still high, yet company earnings are stronger than feared. Your first decision was: <b>${esc(state.investmentChoices[0])}</b>. What matters most now?</p><div class="investment-options"><button class="investment-choice" data-investment-choice="Return to the long-term allocation"><span>A</span><div><b>Return to the long-term allocation</b><small>Rebalance away from decisions driven by the headlines</small></div></button><button class="investment-choice" data-investment-choice="Wait for inflation to fall"><span>B</span><div><b>Wait for clearer inflation data</b><small>Keep flexibility, accepting that prices may move first</small></div></button><button class="investment-choice" data-investment-choice="Chase the strongest sector"><span>C</span><div><b>Move into the strongest sector</b><small>Follow momentum, with greater concentration risk</small></div></button></div><div class="custom-strategy"><label>Or explain your own next move</label><textarea id="custom-investment" maxlength="180" placeholder="What information would you use?"></textarea><button class="btn wide" data-action="submit-custom-investment">Use my strategy</button></div></div>`
 }else{label.textContent='COMPLETE';p.style.width='100%';c.innerHTML=`<div class="investment-result"><div class="result-orb"><b>71%</b><small>PROCESS SCORE</small></div><h2>You managed the uncertainty.</h2><p>The aim was not to guess the market’s next move. It was to make a decision consistent with the time horizon, liquidity needs and risks you were given.</p><div class="decision-recap"><div><span>AFTER THE FALL</span><b>${esc(state.investmentChoices[0])}</b></div><div><span>AFTER THE REBOUND</span><b>${esc(state.investmentChoices[1])}</b></div><div><span>CONCEPTS USED</span><b>Diversification · Time horizon · Rebalancing</b></div></div><p class="uncertainty-note">Simulated outcomes are illustrative. Real markets are uncertain and this is not investment advice.</p><button class="btn primary wide" data-action="close-investment">Finish simulation</button></div>`}
}
function chooseInvestment(choice,button){
 if(state.investmentChoices[state.investmentStep])return;state.investmentChoices[state.investmentStep]=choice;
 $$('.investment-choice').forEach(x=>x.classList.remove('selected'));if(button)button.classList.add('selected');
 const body=$('.investment-body');const feedback=document.createElement('div');feedback.className='investment-feedback';feedback.innerHTML=`<h3>Your reasoning matters more than the prediction</h3><p>${state.investmentStep===0?'With a five-year horizon and a separate cash buffer, short-term volatility may be tolerable—but every option changes the balance between future opportunity and immediate certainty.':'New information is useful, but reacting to every move can pull a plan off course. Rebalancing sets a rule; waiting preserves flexibility; chasing strength increases concentration.'}</p><small>Principle: decisions should connect risk to goals, time and available information.</small><button class="btn primary wide" data-action="investment-next" style="margin-top:12px">Continue →</button>`;body.appendChild(feedback);feedback.scrollIntoView({behavior:'smooth'});
}
function openSimPicker(){
 state.simPickerReturn=$('.screen.active')?.id||'story-screen';
 const advanced=state.level==='Advanced',intermediate=state.level==='Intermediate';
 $('#picker-level').textContent=`${state.level} experience · complexity adapted`;
 $('#trade-level-tag').textContent=advanced?'Advanced market context':intermediate?'Guided order controls':'Extra guidance included';
 $('#trade-mode-label').textContent=advanced?'STOCK TRADING DEMO · 4–5 MIN':'GUIDED TRADING · 3–4 MIN';
 $('#trade-mode-copy').textContent=advanced?'Read price, volume and risk data; size a position; then manage it as the news changes.':'Use a simplified order ticket, read the chart and manage risk as new information arrives.';
 showScreen('simulation-picker-screen');
}
function closeSimPicker(){if(state.simPickerReturn==='calendar-screen')showScreen('calendar-screen');else if(state.simPickerReturn==='story-screen')showScreen('story-screen');else showMain('explore')}
function openTrading(){state.tradingReturn=$('.screen.active')?.id||'simulation-picker-screen';state.tradeRound=0;state.tradeAction='Buy';state.tradeSize=10;state.tradeChoices=[];renderTrading();showScreen('trading-screen')}
function closeTrading(){showScreen(state.tradingReturn||'simulation-picker-screen')}
function tradingChart(reaction=false){return `<div class="terminal-chart ${reaction?'reaction':''}"><div class="chart-labels"><span>154</span><span>150</span><span>146</span></div><svg viewBox="0 0 360 150"><path class="gridline" d="M0 25H360 M0 75H360 M0 125H360"/><path class="trade-line" d="${reaction?'M0 115 C45 104 71 108 103 91 S151 79 181 69 S223 53 252 59 S300 42 360 34':'M0 118 C35 111 61 119 91 98 S140 83 175 89 S220 60 254 66 S305 48 360 40'}"/></svg><button class="chart-news-pin" data-action="trade-marker"><i>!</i><span>${reaction?'NEW DATA':'NEWS'}</span></button><div class="chart-times"><span>09:00</span><span>12:00</span><span>15:30</span></div></div>`}
function renderTrading(){
 const c=$('#trading-content'),label=$('#trade-step-label');$('#trade-cash').textContent=state.tradeRound?`£${(10000-state.tradeSize*10).toLocaleString()}`:'£10,000';
 const advanced=state.level==='Advanced';
 if(state.tradeRound===0){label.textContent='ROUND 1 OF 2';c.innerHTML=`<div class="trading-body"><div class="quote-head"><div><span>MPX</span><h2>£152.46</h2><small class="up">+£1.86 · +1.24% today</small></div><div class="market-open">MARKET OPEN</div></div>${tradingChart()}<button class="news-context" data-action="trade-marker"><span>12:00</span><div><b>Central bank holds rates at 5.25%</b><small>Tap to see why the price moved</small></div><i>›</i></button><div class="terminal-metrics"><div><span>DAY RANGE</span><b>146.80–153.02</b></div><div><span>VOLUME</span><b>18.4m</b></div>${advanced?'<div><span>P/E RATIO</span><b>21.8×</b></div><div><span>VOLATILITY</span><b>High</b></div>':'<div><span>RISK</span><b>High</b></div>'}</div><div class="order-ticket"><div class="ticket-head"><div><b>Your simulated order</b><small>${advanced?'Position sizing and risk controls':'Simple controls, with explanations'}</small></div><span>Virtual</span></div><div class="trade-actions"><button class="${state.tradeAction==='Buy'?'selected':''}" data-trade-action="Buy">Buy</button><button class="${state.tradeAction==='Short'?'selected':''}" data-trade-action="Short">Sell / short</button><button class="${state.tradeAction==='Watch'?'selected':''}" data-trade-action="Watch">Watch</button></div><label class="ticket-label">POSITION SIZE <button data-action="size-help">What’s this?</button></label><div class="size-options">${[5,10,20,30].map(n=>`<button class="${state.tradeSize===n?'selected':''}" data-trade-size="${n}">${n}%<small>£${n*100}</small></button>`).join('')}</div>${advanced?'<div class="risk-row"><label>Risk limit</label><select aria-label="Risk limit"><option>Exit if down 5%</option><option>Exit if down 8%</option><option>No automatic limit</option></select></div>':'<p class="guided-note">Your time horizon is five years. A larger position creates a larger potential gain—and a larger potential loss.</p>'}<button class="btn primary wide" data-action="execute-trade">${state.tradeAction==='Watch'?'Continue without trading':'Place simulated order'} →</button></div><p class="terminal-disclaimer">Simplified educational simulation. No real order is placed and pricing is demonstration data.</p></div>`
 }else if(state.tradeRound===1){label.textContent='ROUND 2 OF 2';const pnl=state.tradeAction==='Buy'?'−£32.10':state.tradeAction==='Short'?'+£32.10':'£0.00';c.innerHTML=`<div class="trading-body"><div class="quote-head"><div><span>MPX · 14:10</span><h2>£147.60</h2><small class="down">−3.19% since your decision</small></div><div class="position-pnl ${state.tradeAction==='Short'?'up':'down'}">${pnl}<small>YOUR P&amp;L</small></div></div>${tradingChart(true)}<div class="breaking-context"><span>NEW INFORMATION</span><b>Services inflation comes in above forecast</b><p>Investors now expect rates to stay high for longer. The index fell because future company profits are worth less when discount rates rise.</p></div><h3 class="trade-prompt">How do you manage the position?</h3><div class="resolution-options"><button data-trade-resolution="Hold and follow the original thesis"><span>HOLD</span><div><b>Keep the position</b><small>The long-term view has not changed</small></div></button><button data-trade-resolution="Close the position and cap the risk"><span>CLOSE</span><div><b>Close the position</b><small>Cap the risk and preserve flexibility</small></div></button><button data-trade-resolution="Add at the lower price"><span>ADD</span><div><b>Add 5% at the lower price</b><small>Increase exposure—and downside risk</small></div></button></div><p class="terminal-disclaimer">The next price move is deliberately unknown. Focus on process, not prediction.</p></div>`
 }else{label.textContent='SIM COMPLETE';c.innerHTML=`<div class="trade-result"><div class="trade-score"><b>${advanced?'84':'76'}</b><small>PROCESS SCORE</small></div><span>SIMULATION COMPLETE</span><h2>You traded the news—not just the chart.</h2><p>You connected a market event to valuation, chose a position size and responded when the facts changed.</p><div class="trade-recap"><div><span>INITIAL ORDER</span><b>${esc(state.tradeChoices[0])}</b></div><div><span>RISK DECISION</span><b>${esc(state.tradeChoices[1])}</b></div><div><span>KEY IDEA</span><b>News changes expectations; expectations change prices.</b></div></div><div class="level-progress"><span>${state.level.toUpperCase()} TRACK</span><b>${advanced?'Advanced market context applied':'Complete more sims to unlock deeper market data'}</b></div><button class="btn primary wide" data-action="close-trading">Finish trading demo</button><p class="terminal-disclaimer">This is deliberately simpler than paper trading and is not investment advice.</p></div>`}
}
function renderMarketWatch(){const order=['MPX','NXT','BNK'];$('#market-watch').innerHTML=order.map(sym=>{const a=marketAssets[sym];return `<button class="${state.marketSymbol===sym?'active':''}" data-market-symbol="${sym}"><span>${sym}</span><b>${a.price.toFixed(2)}</b><small class="${a.change>=0?'up':'down'}">${a.change>=0?'+':''}${a.change.toFixed(2)}%</small></button>`}).join('')}
function renderLiveMarket(){
 renderMarketWatch();const a=marketAssets[state.marketSymbol],m=a.markers[state.marketMarker]||a.markers[0];
 $('#live-market-content').innerHTML=`<div class="live-body"><div class="live-quote"><div><span>${state.marketSymbol}</span><h2 id="live-price">${a.price.toFixed(2)}</h2><small>${a.name}</small></div><div class="${a.change>=0?'up':'down'}"><b>${a.change>=0?'+':''}${a.change.toFixed(2)}%</b><small>TODAY</small></div></div><div class="market-range"><button>1D</button><button class="active">TODAY</button><button>1W</button><button>1M</button></div><div class="live-chart-shell"><div class="live-axis"><span>156</span><span>151</span><span>146</span></div><svg viewBox="0 0 360 180" preserveAspectRatio="none"><path class="market-grid" d="M0 30H360 M0 90H360 M0 150H360"/><path class="market-line" style="stroke:${a.color}" d="${a.path}"/></svg>${a.markers.map((pin,i)=>`<button class="news-pin ${i===state.marketMarker?'active':''}" style="left:${pin.x}%;top:${pin.y}%" data-news-marker="${i}"><i>${i+1}</i><span>${pin.time}</span></button>`).join('')}</div><div class="marker-detail"><div class="marker-detail-top"><span>NEWS MARKER ${state.marketMarker+1} · ${m.time}</span><b class="${m.move.startsWith('+')?'up':'down'}">${m.move}</b></div><h3>${m.title}</h3><p>${m.story}</p><div class="marker-price"><span>PRICE AT EVENT</span><b>${m.price}</b><i>→</i><button data-action="marker-story">Explore story</button></div><small class="causality-note">Why, not certainty: this is the strongest evidenced explanation. Other market forces may also have contributed.</small></div><div class="market-explainer"><span>HOW TO READ THIS</span><div><i>1</i><p><b>News lands</b><small>A verified event changes available information.</small></p></div><div><i>2</i><p><b>Expectations shift</b><small>Investors update forecasts for risk, rates or profit.</small></p></div><div><i>3</i><p><b>Price finds a new level</b><small>Buyers and sellers respond—often imperfectly.</small></p></div></div><p class="terminal-disclaimer">Simulated live data for product demonstration. Not a real-time market feed.</p></div>`;
}
function startLiveMarket(){state.liveReturn=$('.screen.active')?.id||'main-screen';state.marketMarker=1;renderLiveMarket();showScreen('live-market-screen');clearInterval(state.liveTimer);state.liveTimer=setInterval(()=>{const a=marketAssets[state.marketSymbol];a.price=Math.max(1,a.price+(Math.random()-.48)*.09);const el=$('#live-price');if(el){el.textContent=a.price.toFixed(2);el.classList.add('tick');setTimeout(()=>el.classList.remove('tick'),250)}},3000)}
function closeLiveMarket(){clearInterval(state.liveTimer);state.liveReturn==='main-screen'?showMain('explore'):showScreen(state.liveReturn||'main-screen')}
const slideData=[
 {type:'cover',html:`<div class="slide-kicker">ECONOMY · DEMONSTRATION STORY</div><h1>Rates stay higher as inflation proves stubborn</h1><p>The central bank held its main rate at 5.25%. The surprise was its warning: price pressures may take longer to cool.</p><div class="confidence"><i></i><span><b>High confidence</b><br>Confirmed by the central bank and four independent sources</span></div>`},
 {html:`<div class="slide-kicker">01 · WHAT HAPPENED?</div><h2>No cut—despite hopes for relief</h2><p>Policymakers voted to keep interest rates unchanged. Investors had largely expected that. What moved markets was the cautious tone about future cuts.</p><div class="big-stat"><b>5.25%</b><small>POLICY RATE · UNCHANGED</small></div><div class="source-box"><b>Confirmed fact</b> · Central bank policy statement, 12:00 BST</div>`},
 {html:`<div class="slide-kicker">02 · WHY DID IT HAPPEN?</div><h2>Inflation is falling—but not evenly</h2><p>Headline inflation has cooled, yet service prices and wage growth remain stronger than policymakers would like.</p><div class="comparison"><div><small>HEADLINE INFLATION</small><b class="down">2.3%</b><span>Closer to target</span></div><div><small>SERVICES INFLATION</small><b>5.9%</b><span>Still sticky</span></div></div><div class="simple-chart"><svg viewBox="0 0 320 150"><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#ff3b3f" stop-opacity=".3"/><stop offset="1" stop-color="#ff3b3f" stop-opacity="0"/></linearGradient></defs><path class="area" d="M0 38 C45 45 65 36 105 70 S175 98 210 87 S265 112 320 123 L320 150 L0 150Z"/><path d="M0 38 C45 45 65 36 105 70 S175 98 210 87 S265 112 320 123"/></svg></div><div class="source-box"><b>Analysis</b> · The path of future inflation remains uncertain.</div>`},
 {html:`<div class="slide-kicker">03 · WHY DOES IT MATTER?</div><h2>One rate. Millions of knock-on effects.</h2><p>The policy rate influences how expensive it is to borrow and how rewarding it is to save.</p><div class="impact-list"><div><span>⌂</span><div><b>Borrowers</b><small>Mortgages and business loans may stay expensive for longer.</small></div></div><div><span>£</span><div><b>Savers</b><small>Cash savings can continue to earn relatively higher returns.</small></div></div><div><span>↗</span><div><b>Markets</b><small>Higher yields can make shares, especially growth companies, less attractive.</small></div></div></div>`},
 {html:`<div class="slide-kicker">04 · TERM TO KNOW</div><div class="term-card"><span class="term">“Sticky” inflation</span><p>Prices that are slow to cool even when the wider inflation rate is falling. Services—like rent, restaurants and haircuts—often change more slowly than goods.</p></div><div class="quick-toggle"><button class="active">Quick</button><button data-action="deeper-term">Deeper</button></div><p id="deeper-copy">Think of it like glitter: the biggest pieces are easy to clear, but some cling on. Policymakers want evidence those last price pressures are fading before cutting.</p><div class="source-box"><b>Beginner explanation</b> · Matched to your selected level</div>`},
 {html:`<div class="slide-kicker">05 · WHAT NEXT?</div><h2>The next data matters more than the next prediction</h2><p>Watch wage growth, services inflation and the next policy meeting. A single data point rarely decides the path.</p><div class="story-end-actions"><button data-action="open-activity">Try it · Make 2 decisions →</button><button data-action="open-sim-picker">↗ Choose an investment simulation</button><button data-action="open-live-market">⌁ View the news on the live chart</button><button data-action="open-ai">✦ Ask MarketPlay about this story</button><button data-action="open-history">◷ Experience a similar moment in history</button></div><div class="source-box"><b>Sources</b> · Central bank statement · National statistics office · Reuters · BBC News<br><br>Last checked 8 minutes ago · Demonstration content</div>`}
];
function openStory(i=0){state.storyReturn=$('.screen.active')?.id||'main-screen';state.currentStory=i;state.currentSlide=0;renderStory();showScreen('story-screen')}
function closeStory(){if(state.storyReturn==='calendar-screen')showScreen('calendar-screen');else if(state.storyReturn==='live-market-screen')showScreen('live-market-screen');else showMain('today')}
function renderStory(){
 const story=stories[state.currentStory];const slides=state.currentStory===0?slideData:[{type:'cover',html:`<div class="slide-kicker">${story.tag} · DEMONSTRATION STORY</div><h1>${story.headline}</h1><p>${story.summary}</p><div class="confidence"><i></i><span><b>Demo preview</b><br>Open the lead rates story for the full six-part experience.</span></div>`},{html:`<div class="slide-kicker">QUICK EXPLAINER</div><h2>Why this moved the market</h2><p>This preview demonstrates story navigation. The lead rates story includes verified facts, analysis, market effects, a term card and interactive activities.</p><div class="story-end-actions"><button data-action="close-story">Return to today →</button><button data-action="open-ai">✦ Ask MarketPlay</button></div>`}];
 $('#story-slides').innerHTML=slides.map((s,i)=>`<article class="story-slide ${s.type||''} ${i===state.currentSlide?'active':''}" style="${s.type==='cover'?`background-image:linear-gradient(transparent,#080a0d),url('${story.art==='art-chip'?'assets/semiconductor.png':'assets/central-bank.png'}')`:''}">${s.html}</article>`).join('');
 $('#story-progress').innerHTML=slides.map((_,i)=>`<i class="${i<state.currentSlide?'done':i===state.currentSlide?'current':''}"></i>`).join('');$('#story-count').textContent=`${state.currentSlide+1} / ${slides.length}`;
}
function changeSlide(dir){const n=state.currentStory===0?slideData.length:2;state.currentSlide=Math.max(0,Math.min(n-1,state.currentSlide+dir));renderStory()}
function renderActivity(){const c=$('#activity-content'), p=$('.activity-progress i'), lab=$('.activity-step');if(state.activityStep===0){lab.textContent='1 / 2';p.style.width='50%';c.innerHTML=`<div class="activity-body"><span class="scenario-label">DECISION 1 · BORROWING</span><h2>You run a growing coffee company.</h2><p>You planned to borrow £100,000 for a second shop. Rates have stayed high. What do you do?</p><div class="scenario-card"><div class="metric-row"><span>Loan rate</span><b class="down">8.2%</b></div><div class="metric-row"><span>Expected annual profit from new shop</span><b>£14,000</b></div><div class="metric-row"><span>Economic outlook</span><b>Uncertain</b></div></div><div class="decision-stack"><button class="decision" data-decision="borrow"><span>A</span><div><b>Borrow and expand now</b><small>Move fast before a competitor takes the location</small></div></button><button class="decision" data-decision="wait"><span>B</span><div><b>Wait six months</b><small>Keep the cash buffer and reassess demand</small></div></button></div><p class="disclaimer">Educational simulation—not financial advice. Outcomes are uncertain.</p></div>`}else if(state.activityStep===1){lab.textContent='2 / 2';p.style.width='100%';c.innerHTML=`<div class="activity-body"><span class="scenario-label">DECISION 2 · PRICING</span><h2>Your costs just rose 6%.</h2><p>Customers are becoming price-sensitive. How do you protect the business?</p><div class="scenario-card"><div class="metric-row"><span>Ingredient costs</span><b class="down">+6%</b></div><div class="metric-row"><span>Customer visits</span><b class="down">−2%</b></div><div class="metric-row"><span>Current margin</span><b>12%</b></div></div><div class="decision-stack"><button class="decision" data-decision="raise"><span>A</span><div><b>Raise every price by 6%</b><small>Pass the full cost increase to customers</small></div></button><button class="decision" data-decision="mix"><span>B</span><div><b>Use a targeted mix</b><small>Adjust selected prices and trim lower-value costs</small></div></button></div></div>`}else{lab.textContent='COMPLETE';c.innerHTML=`<div class="activity-complete"><div class="complete-orb">✓</div><h2>Scenario complete</h2><p>You balanced the cost of borrowing with uncertainty and protected flexibility—two ideas central to higher-rate environments.</p><span class="xp">+40 LEARNING XP</span><button class="btn primary wide" data-action="close-activity">Return to story</button></div>`}}
function activityFeedback(choice){const c=$('.activity-body');const feedback=document.createElement('div');feedback.className='feedback';const first=state.activityStep===0;feedback.innerHTML=`<h3>${choice==='wait'||choice==='mix'?'Thoughtful trade-off':'Bold choice—check the downside'}</h3><p>${first?'Waiting protects cash if demand weakens, but risks losing a strong location. Borrowing may still work if the return comfortably exceeds the financing cost.':'A targeted approach can protect margin without treating every product or customer the same. A full price rise is simpler, but may weaken demand.'}</p><div class="principle"><b>PRINCIPLE:</b> ${first?'Hurdle rate — an investment should earn more than its cost of capital, with room for uncertainty.':'Pricing power — the ability to raise prices without losing too much demand.'}</div><button class="btn primary wide" data-action="activity-next" style="margin-top:14px">Continue →</button>`;$$('.decision').forEach(b=>b.disabled=true);c.appendChild(feedback);feedback.scrollIntoView({behavior:'smooth'})}
function renderHistory(){const c=$('#history-content');if(!state.historyDone){c.innerHTML=`<div class="history-body"><span class="date-line">15 September 2008 · 08:30 New York</span><h2>A major bank has collapsed.</h2><p>You are managing a cautious university endowment. Markets have opened sharply lower—but nobody knows how far the damage will spread.</p><div class="news-wire"><span>NEWS WIRE · WHAT YOU KNOW NOW</span><h3>Lehman Brothers files for bankruptcy protection</h3><p>Officials failed to secure a buyer over the weekend. Counterparties are assessing their exposure. Other banks say they remain well-capitalised.</p></div><div class="known-box"><b>AVAILABLE INFORMATION</b><ul><li>Global shares are down 3–5%</li><li>Credit markets are becoming harder to trade</li><li>Cash is yielding about 2%</li></ul></div><h3>What do you do?</h3><button class="history-choice" data-history-choice="hold"><b>Hold the current allocation</b><small>Avoid making a big decision during panic</small></button><button class="history-choice" data-history-choice="cash"><b>Move 20% into cash</b><small>Reduce immediate risk and protect liquidity</small></button><button class="history-choice" data-history-choice="buy"><b>Buy more global shares</b><small>Prices are lower; think beyond the panic</small></button><p class="disclaimer">You only see information available at the time.</p></div>`}else{c.innerHTML=`<div class="history-body history-result"><span class="date-line">WHAT HAPPENED NEXT</span><h2>The crisis spread through the financial system.</h2><p>Your decision protected some flexibility, but no option was risk-free. Markets fell much further before eventually recovering.</p><div class="timeline"><div><b>29 September 2008</b><small>US shares suffer one of their largest single-day falls.</small></div><div><b>October 2008</b><small>Governments announce bank rescues and central banks cut rates.</small></div><div><b>9 March 2009</b><small>Major share indices reach their crisis lows.</small></div><div><b>Following years</b><small>Markets recover unevenly as policy support takes effect.</small></div></div><div class="comparison"><div><small>GLOBAL SHARES</small><b class="down">−42%</b><span>Sep 08–Mar 09</span></div><div><small>10 YEARS LATER</small><b class="up">+151%</b><span>Illustrative global index</span></div></div><div class="history-note">History does not tell us what will happen next. It helps us understand the factors that may matter.</div><button class="btn primary wide" data-action="close-history" style="margin-top:18px">Finish simulation</button></div>`}}
function askAI(q){if(!q.trim())return;const chat=$('#chat');chat.insertAdjacentHTML('beforeend',`<div class="user-bubble">${q.replace(/[<>]/g,'')}</div>`);const answers={simpler:'The central bank kept borrowing costs high because some prices—especially services—are still rising too quickly. It wants more proof inflation is cooling before making loans cheaper.',markets:'Investors had hoped rate cuts might come sooner. When the bank sounded cautious, bond yields rose and rate-sensitive shares slipped.',affected:'Mortgage borrowers, businesses with loans and growth companies feel pressure. Savers may benefit from higher deposit rates.',before:'Yes. In the 1970s and early 1980s, policymakers also faced persistent inflation—but today’s causes, institutions and financial system are different.'};let key=Object.keys(answers).find(k=>q.toLowerCase().includes(k));let ans=answers[key]||'The key tension is timing: cutting too early could let inflation persist, while waiting too long could weaken jobs and growth. Policymakers are weighing both risks.';setTimeout(()=>{chat.insertAdjacentHTML('beforeend',`<div class="ai-bubble"><div class="ai-mark">M↗</div><div><p>${ans}</p><div class="answer-sources">Sources: Central bank statement · National statistics office · Reuters</div></div></div>`);chat.lastElementChild.scrollIntoView({behavior:'smooth'})},350)}
function showState(type){const map={offline:['⌁','You’re offline','Saved stories are still available. Reconnect to refresh prices and breaking news.','Try again'],error:['!','Something moved unexpectedly','We couldn’t load this story. Your place in the feed is safe.','Reload story'],loading:['spinner','Checking the latest facts','Comparing sources and refreshing market data…','']};const d=map[type];$('#state-content').innerHTML=`<div class="state-visual">${d[0]==='spinner'?'<div class="spinner"></div>':d[0]}</div><h2>${d[1]}</h2><p>${d[2]}</p>${d[3]?`<button class="btn primary" data-action="close-state">${d[3]}</button>`:''}`;showScreen('state-screen');if(type==='loading')setTimeout(()=>showMain('today'),1600)}
document.addEventListener('click',e=>{
 const card=e.target.closest('.news-card');if(card&&!e.target.closest('button')){openStory(+card.dataset.story);return}
 const b=e.target.closest('button');if(!b)return;const a=b.dataset.action;
 if(b.dataset.calendarDay){state.calendarDay=+b.dataset.calendarDay;renderCalendar();return}
 if(b.dataset.archiveStory!==undefined){openStory(+b.dataset.archiveStory);return}
 if(b.dataset.investment!==undefined){openSimPicker();return}
 if(b.dataset.investmentChoice){chooseInvestment(b.dataset.investmentChoice,b);return}
 if(b.dataset.marketSymbol){state.marketSymbol=b.dataset.marketSymbol;state.marketMarker=0;renderLiveMarket();return}
 if(b.dataset.newsMarker!==undefined){state.marketMarker=+b.dataset.newsMarker;renderLiveMarket();return}
 if(b.dataset.tradeAction){state.tradeAction=b.dataset.tradeAction;renderTrading();return}
 if(b.dataset.tradeSize){state.tradeSize=+b.dataset.tradeSize;renderTrading();return}
 if(b.dataset.tradeResolution){state.tradeChoices[1]=b.dataset.tradeResolution;state.tradeRound=2;renderTrading();return}
 if(b.dataset.nav){showMain(b.dataset.nav);return}if(b.dataset.openStory!==undefined){openStory(+b.dataset.openStory);return}
 if(b.dataset.save!==undefined){const i=+b.dataset.save;state.saved.has(i)?state.saved.delete(i):state.saved.add(i);renderFeed();renderSaved();toast(state.saved.has(i)?'Saved to your library':'Removed from saved');return}
 if(b.dataset.share!==undefined){navigator.clipboard?.writeText('MarketPlay demo story');toast('Story link copied');return}if(b.dataset.hide!==undefined){toast('We’ll show fewer stories like this');return}
 if(b.classList.contains('level-card')){$$('.level-card').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.level=b.dataset.level;return}
 if(b.classList.contains('topic')){b.classList.toggle('selected');state.topics=$$('.topic.selected').length;$('#topic-count').textContent=`${state.topics} selected`;return}
 if(b.closest('.feed-tabs')){$$('.feed-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');toast(b.textContent.trim()==='For you'?'Your personalised feed':`${b.textContent.trim()} selected`);return}
 if(b.closest('.billing-toggle')){$$('.billing-toggle button').forEach(x=>x.classList.remove('active'));b.classList.add('active');toast(`${b.textContent.trim()} billing selected`);return}
 if(b.closest('.quick-toggle')){$$('.quick-toggle button').forEach(x=>x.classList.remove('active'));b.classList.add('active');if(b.textContent.trim()==='Deeper')$('#deeper-copy').textContent='Services inflation often responds to labour costs, productivity and expectations. Central banks look at persistence across several indicators rather than reacting to one headline print.';return}
 if(b.closest('.suggested')){askAI(b.textContent);return}if(b.dataset.decision){activityFeedback(b.dataset.decision);return}if(b.dataset.historyChoice){state.historyDone=true;renderHistory();return}
 const acts={
 'onboard-next':()=>showScreen('level-screen'),'onboard-back':()=>showScreen('onboarding'),'level-next':()=>showScreen('interests-screen'),'interests-back':()=>showScreen('level-screen'),
 'demo-feed':()=>showMain(),'finish-onboarding':()=>{if(state.topics<3){toast('Choose at least 3 topics');return}$('#profile-level').textContent=state.level;showMain()},
 'close-story':()=>closeStory(),'prev-slide':()=>changeSlide(-1),'next-slide':()=>changeSlide(1),'story-audio':()=>toast('Audio narration started'),'audio-toast':()=>toast('Playing your 2-minute briefing'),
 'open-ai':()=>showScreen('ai-screen'),'close-ai':()=>showScreen('story-screen'),'ai-info':()=>toast('Answers use verified story sources'),
 'open-activity':()=>{state.activityStep=0;renderActivity();showScreen('activity-screen')},'close-activity':()=>showScreen('story-screen'),'activity-next':()=>{state.activityStep++;renderActivity()},
 'open-history':()=>{state.historyDone=false;renderHistory();showScreen('history-screen')},'close-history':()=>showScreen('story-screen'),
 'open-calendar':()=>{renderCalendar();showScreen('calendar-screen')},'close-calendar':()=>showMain('explore'),'calendar-info':()=>toast('The archive stores each day from launch'),'calendar-prev':()=>toast('Archive begins in August 2026'),'archive-filter':()=>{const filters=['All','Stories','Simulations'];state.archiveFilter=filters[(filters.indexOf(state.archiveFilter)+1)%filters.length];renderArchiveDay()},
 'open-sim-picker':()=>openSimPicker(),'close-sim-picker':()=>closeSimPicker(),'start-quick-sim':()=>openInvestment(),'start-trading-sim':()=>openTrading(),
 'open-investment':()=>openInvestment(),'close-investment':()=>showScreen(state.investmentReturn||'calendar-screen'),'investment-next':()=>{state.investmentStep++;renderInvestment()},'submit-custom-investment':()=>{const input=$('#custom-investment');if(!input.value.trim()){toast('Describe your idea first');return}chooseInvestment(`My idea: ${input.value.trim()}`,null)},
 'close-trading':()=>closeTrading(),'trading-help':()=>toast('A guided simulation—not real paper trading'),'trade-marker':()=>toast('The rate decision reduced fears of another increase'),'size-help':()=>toast('Position size is the share of virtual cash at risk'),'execute-trade':()=>{state.tradeChoices[0]=`${state.tradeAction} · ${state.tradeSize}% position`;state.tradeRound=1;renderTrading()},
 'open-live-market':()=>startLiveMarket(),'close-live-market':()=>closeLiveMarket(),'market-info':()=>toast('Prices update with simulated ticks'),'marker-story':()=>openStory(0),
 'open-premium':()=>showScreen('premium-screen'),'close-premium':()=>showMain('profile'),'start-trial':()=>{toast('Demo trial activated');setTimeout(()=>showMain('profile'),800)},
 'state-loading':()=>showState('loading'),'state-offline':()=>showState('offline'),'state-error':()=>showState('error'),
 'close-state':()=>showMain('today'),'show-search':()=>$('#search-input').focus(),'saved-menu':()=>toast('Saved story options'),'settings':()=>toast('Settings are ready'),'change-level':()=>showScreen('level-screen'),'attention-info':()=>toast('Based on stories you explored'),'deeper-term':()=>{},
 };
 if(acts[a])acts[a]();
});
$('#chat-form').addEventListener('submit',e=>{e.preventDefault();const q=$('#chat-question');askAI(q.value);q.value=''});
let touchX=0;$('#story-slides').addEventListener('touchstart',e=>touchX=e.touches[0].clientX,{passive:true});$('#story-slides').addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-touchX;if(Math.abs(dx)>55)changeSlide(dx<0?1:-1)},{passive:true});
renderFeed();renderSaved();renderActivity();renderHistory();renderCalendar();renderInvestment();
// Expose prototype states for review from the console: MarketPlay.showState('offline'|'error'|'loading')
window.MarketPlay={showState,openStory,showMain};
